### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by nickhristov** [britt/github-java#1]
mvn install fails with multiple compilations issues. All seem to revolve around an unknown symbol JSON.

**Comment by britt** [comment]
Was there a problem fetching the org.json JSON jar when you installed?  

I am unable to replicate this locally. I tried removing the JSON jar from my local maven repository to force the download and still had no problems.

**Comment by britt** [comment]
Oh I see, I should've paid closer attention.  The actual json.java file was not included in the repository.

Thanks for the patch!
